image: node:14.17.5

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

build-dependencies:
  stage: build
  script: 
    - npm install
    - npm run build
    - npm i firebase-tools -g

deploy_staging:
  only:
    - branches
  stage: staging
  environment: staging
  when: manual
  needs: [build-dependencies]
  script:
    - firebase hosting:channel:deploy $CI_BUILD_REF_NAME --token $K8S_SECRET_FIREBASE_TOKEN

deploy_firebase:
  only:
    - main
  stage: deploy
  environment: production
  needs: [build-dependencies]
  script:
    - firebase deploy --token $K8S_SECRET_FIREBASE_TOKEN
